# -*- coding: utf-8 -*-
"""GEO análise.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Bd0JnSex_CdrdtuF_H1TpcJVLeIS4WOs

#Código Básico:
"""

!pip install GEOparse

import pandas as pd
import GEOparse
import pylab as pl
import seaborn as sns
import re
import numpy as np
from google.colab import drive
import statsmodels
import statsmodels.api as sm
import statsmodels.formula.api as smfs
import scipy.stats as stats

drive.mount('/content/drive')

lista_gse_bruto=[]
text=open("/content/drive/My Drive/gds_result.txt")
a=text.read().split()
for i in range(len(a)):
  if a[i].startswith('GSE')==True:
    lista_gse_bruto.append(a[i])

lista_gse=np.unique(lista_gse_bruto).tolist()

#Organizando o backgroud do gráfico:

pl.rcParams['figure.figsize'] = (14, 10)
pl.rcParams['ytick.labelsize'] = 12
pl.rcParams['xtick.labelsize'] = 11
pl.rcParams['axes.labelsize'] = 23
pl.rcParams['legend.fontsize'] = 20
sns.set_style('ticks')
c1, c2, c3, c4 = sns.color_palette("Set1", 4)

"""#GSE104006"""

#miRNA and gene expression profiling in human thyroid carcinomas and non-neoplastic thyroids:
gse = GEOparse.get_GEO(lista_gse[2])

gse.gpls['GPL14951'].columns

gse.gsms["GSM2787513"].columns

gse.phenotype_data[["title", "source_name_ch1"]].query("source_name_ch1 == 'Non-neoplastic_thyroid'")

#Gerando a lista dos controles:
controls = ['GSM2787544', 'GSM2787543', 'GSM2787536', 'GSM2787533', 'GSM2787524', 'GSM2787520']

pivoted_control_samples = gse.pivot_samples('VALUE')[controls]

pivoted_control_samples.hist()
sns.despine(offset=10, trim=True)

gse.phenotype_data['characteristics_ch1.1.histology'].unique()

mirna_samples=gse.phenotype_data
mirna_samples_short=mirna_samples[['title','submission_date',	'last_update_date','characteristics_ch1.1.histology','characteristics_ch1.2.age','characteristics_ch1.3.Sex','extract_protocol_ch1','contact_name','contact_country']]

neoplasic_samples=mirna_samples_short[mirna_samples_short['characteristics_ch1.1.histology'].str.startswith('Non')==False]

neoplasic_samples=neoplasic_samples[neoplasic_samples['title'].str.endswith('[miRNA]')]

neoplasic=neoplasic_samples.index.tolist()
pivoted_neoplasic_samples = gse.pivot_samples('VALUE')[neoplasic]

"""Principais variáveis que gerei:
> *controls* - lista dos GSM dos controles

> *neoplasic* - lista dos GSM das amostras neoplasicas

> *neoplasic_samples* - lista das principais informações das amostras neoplasicas

> *non_neoplasic_samples* - lista das principais informações das amostras controle

> *pivoted_neoplasic_samples* - log2 da expressão dos miRNA nas amostras neoplasicas

> *pivoted_control_samples* - log2 da expressão dos miRNA nas amostras controle




"""

PDTC_GSM=neoplasic_samples[neoplasic_samples['characteristics_ch1.1.histology']=='PDTC'].index.tolist()
PTC_GSM=neoplasic_samples[neoplasic_samples['characteristics_ch1.1.histology']=='PTC'].index.tolist()
PTC_lymph_node_metastasis_GSM=neoplasic_samples[neoplasic_samples['characteristics_ch1.1.histology']=='PTC_lymph_node_metastasis'].index.tolist()
PTC_PDTC_GSM=["GSM2787534", "GSM2787522"]

"""Média e desvio padrão por categoria histológica:"""

#PTC:
pivoted_PTC_samples = pivoted_neoplasic_samples[PTC_GSM]
pivoted_PTC_samples['Mean log2 expression']=pivoted_PTC_samples.mean(axis=1)
pivoted_PTC_samples['Standard Deviation log2 expression']=pivoted_PTC_samples.std(axis=1)
pivoted_PTC_samples_statistics=pivoted_PTC_samples[['Mean log2 expression','Standard Deviation log2 expression']].dropna()
pivoted_PTC_samples_statistics

#PDTC:
pivoted_PDTC_samples = pivoted_neoplasic_samples[PDTC_GSM]
pivoted_PDTC_samples['Mean log2 expression']=pivoted_PDTC_samples.mean(axis=1)
pivoted_PDTC_samples['Standard Deviation log2 expression']=pivoted_PDTC_samples.std(axis=1)
pivoted_PDTC_samples_statistics=pivoted_PDTC_samples[['Mean log2 expression','Standard Deviation log2 expression']].dropna()

#PTC_lymph_node_metastasis:
pivoted_PTC_lymph_node_metastasis_samples = pivoted_neoplasic_samples[PTC_lymph_node_metastasis_GSM]
pivoted_PTC_lymph_node_metastasis_samples['Mean log2 expression']=pivoted_PTC_lymph_node_metastasis_samples.mean(axis=1)
pivoted_PTC_lymph_node_metastasis_samples['Standard Deviation log2 expression']=pivoted_PTC_lymph_node_metastasis_samples.std(axis=1)
pivoted_PTC_lymph_node_metastasis_samples_statistics=pivoted_PTC_lymph_node_metastasis_samples[['Mean log2 expression','Standard Deviation log2 expression']].dropna()

#PTC+PDTC:
pivoted_PTC_PDTC_samples = pivoted_neoplasic_samples[PTC_PDTC_GSM]
pivoted_PTC_PDTC_samples['Mean log2 expression']=pivoted_PTC_PDTC_samples.mean(axis=1)
pivoted_PTC_PDTC_samples['Standard Deviation log2 expression']=pivoted_PTC_PDTC_samples.std(axis=1)
pivoted_PTC_PDTC_samples_statistics=pivoted_PTC_PDTC_samples[['Mean log2 expression','Standard Deviation log2 expression']].dropna()

"""Média e desvio padrão controle:"""

#Controle:
pivoted_control_samples['Mean log2 expression']=pivoted_control_samples.mean(axis=1)
pivoted_control_samples['Standard Deviation log2 expression']=pivoted_control_samples.std(axis=1)
pivoted_control_samples_statistics=pivoted_control_samples[['Mean log2 expression','Standard Deviation log2 expression']].dropna()

"""Obtendo o log2FC"""

#log2FC (PTC/Controle)
log2fc_ptc_control=pd.DataFrame(pivoted_control_samples_statistics['Mean log2 expression'] - pivoted_control_samples_statistics['Mean log2 expression'])
log2fc_ptc_control.columns=['log2FC (PTC/control)']
#log2FC (PDTC/Controle)
log2fc_pdtc_control=pd.DataFrame(pivoted_PDTC_samples_statistics['Mean log2 expression'] - pivoted_control_samples_statistics['Mean log2 expression'])
log2fc_pdtc_control.columns=['log2FC (PDTC/control)']
#log2FC (PTC_lymph_node_metastasis/Controle)
log2fc_PTC_lymph_node_metastasis_control=pd.DataFrame(pivoted_PTC_lymph_node_metastasis_samples_statistics['Mean log2 expression'] - pivoted_control_samples_statistics['Mean log2 expression'])
log2fc_PTC_lymph_node_metastasis_control.columns=['log2FC (PTC lymph node metastasis/control)']
#log2FC (PTC+PDTC/Controle)
log2fc_PTC_PDTC_control=pd.DataFrame(pivoted_PTC_PDTC_samples_statistics['Mean log2 expression'] - pivoted_control_samples_statistics['Mean log2 expression'])
log2fc_PTC_PDTC_control.columns=['log2FC (PTC+PDTC/control)']

"""Fazendo teste-t e p-ajustado:"""

temp1=pivoted_neoplasic_samples[PTC_lymph_node_metastasis_GSM]
temp1=temp1[temp1.index.str.startswith('hsa')].dropna()
temp2=pivoted_control_samples[controls]
temp2=temp2[temp2.index.str.startswith('hsa')].dropna()
temp3=log2fc_PTC_lymph_node_metastasis_control

st, p = stats.ttest_ind(a=temp1,b=temp2, axis=1)
p_test=pd.DataFrame(data=p, index=temp1.index.tolist(), columns=['p-valor'])
b=pd.merge(temp3, p_test, how='outer', left_index=True, right_index=True )

a = statsmodels.stats.multitest.multipletests(pvals=p, method='fdr_bh')
p_test_adjusted=pd.DataFrame(data=a[1].tolist(), index=temp1.index.tolist(), columns=['p-valor ajustado'])

metastasis = pd.merge(b, p_test_adjusted, how='outer', left_index=True, right_index=True).drop_duplicates()
metastasis[metastasis['p-valor ajustado']<0.05].sort_values(by='log2FC (PTC lymph node metastasis/control)')

"""#GSE113629"""

#miRNA and gene expression profiling in human thyroid carcinomas and non-neoplastic thyroids:
gse = GEOparse.get_GEO(lista_gse[3])

gse.gpls['GPL24741'].columns

gse.gsms["GSM3110479"].columns

a=gse.phenotype_data.columns.tolist()
a[11]='Histological Type'
gse.phenotype_data.columns=a

#Gerando a lista dos controles:
temp = gse.phenotype_data[["title", "Histological Type"]]
controls = temp[temp['Histological Type']=='normal thyroid tissue without tumor cell invasion'].index.tolist()

pivoted_control_samples = gse.pivot_samples('VALUE')[controls]

pivoted_control_samples.hist()
sns.despine(offset=10, trim=True)

neoplasic=['GSM3110474', 'GSM3110475', 'GSM3110476', 'GSM3110477', 'GSM3110478']
pivoted_neoplasic_samples = gse.pivot_samples('VALUE')[neoplasic]

#histologia, idade, sexo, protocolo de extração, autor, país
temp=gse.phenotype_data[['submission_date','last_update_date','source_name_ch1', 'Histological Type','characteristics_ch1.2.gender','characteristics_ch1.3.age','contact_name','contact_country']]
neoplasic_samples=temp[temp['Histological Type']== 'papillary thyroid carcinoma']
non_neoplasic_samples=temp[temp['Histological Type']== 'normal thyroid tissue without tumor cell invasion']

"""Principais variáveis que gerei:
> *controls* - lista dos GSM dos controles

> *neoplasic* - lista dos GSM das amostras neoplasicas

> *neoplasic_samples* - lista das principais informações das amostras neoplasicas

> *non_neoplasic_samples* - lista das principais informações das amostras controle

> *pivoted_neoplasic_samples* - log2 da expressão dos miRNA nas amostras neoplasicas

> *pivoted_control_samples* - log2 da expressão dos miRNA nas amostras controle

Média e desvio padrão por categoria histológica:
"""

#PTC:
pivoted_neoplasic_samples = gse.pivot_samples('VALUE')[neoplasic]
pivoted_neoplasic_samples['Mean log2 expression']=pivoted_neoplasic_samples.mean(axis=1)
pivoted_neoplasic_samples['Standard Deviation log2 expression']=pivoted_neoplasic_samples.std(axis=1)
pivoted_neoplasic_samples_statistics=pivoted_neoplasic_samples[['Mean log2 expression','Standard Deviation log2 expression']].dropna()

"""Média e desvio padrão controle:"""

#Controle:
gse_control = GEOparse.get_GEO(lista_gse[3])

pivoted_controls_samples = gse_control.pivot_samples('VALUE')[controls]
pivoted_controls_samples['Mean log2 expression']=pivoted_controls_samples.mean(axis=1)
pivoted_controls_samples['Standard Deviation log2 expression']=pivoted_controls_samples.std(axis=1)
pivoted_controls_samples_statistics=pivoted_controls_samples[['Mean log2 expression','Standard Deviation log2 expression']].dropna()

"""Obtendo o log2FC"""

#log2FC (PTC/Controle)
log2fc_ptc_control=pd.DataFrame(pivoted_neoplasic_samples_statistics['Mean log2 expression'] - pivoted_controls_samples_statistics['Mean log2 expression'])
log2fc_ptc_control.columns=['log2FC (PTC/control)']

"""Tabelando os up e down regulated miR:"""

#PTC:
miR_upregulated_PTC=log2fc_ptc_control[log2fc_ptc_control>float(log2fc_ptc_control.quantile(0.975))].dropna()
miR_downregulated_PTC=log2fc_ptc_control[log2fc_ptc_control<float(log2fc_ptc_control.quantile(0.025))].dropna()

"""T-test:"""

#sts.multitest.multipletests()
st, p = stats.ttest_ind(a=pivoted_controls_samples[['GSM3110479', 'GSM3110480', 'GSM3110481', 'GSM3110482', 'GSM3110483']],b=pivoted_neoplasic_samples[['GSM3110474', 'GSM3110475', 'GSM3110476', 'GSM3110477', 'GSM3110478']], axis=1)
p_test=pd.DataFrame(data=p, index=pivoted_controls_samples.index.tolist(), columns=['p-valor'])
a = statsmodels.stats.multitest.multipletests(pvals=p, method='fdr_bh')
p_test_adjusted=pd.DataFrame(data=a[1].tolist(), index=pivoted_controls_samples.index.tolist(), columns=['p-valor ajustado'])

"""Final:"""

miR_PTC=pd.concat([miR_upregulated_PTC, miR_downregulated_PTC])
miR_PTC=pd.merge(miR_PTC, p_test, how='inner', left_index=True, right_index=True)
miR_PTC=pd.merge(miR_PTC, p_test_adjusted, how='inner', left_index=True, right_index=True)
miR_PTC.sort_values(by='log2FC (PTC/control)')

"""#GSE129878"""

#miRNA and gene expression profiling in human thyroid carcinomas and non-neoplastic thyroids:
gse = GEOparse.get_GEO(lista_gse[6])

gse.gpls['GPL19117'].columns

gse.gsms["GSM3723850"].columns

gse.phenotype_data['source_name_ch1'].unique()

#histologia, idade, sexo, protocolo de extração, autor, país
gse.phenotype_data.columns
neoplasic_samples=gse.phenotype_data[['submission_date','last_update_date','source_name_ch1','characteristics_ch1.2.age','characteristics_ch1.3.gender','contact_name','contact_country']]

temp=gse.gpls['GPL19117'].table.sort_values(by='ID').reset_index(drop=True)

gse.pivot_samples('VALUE').index[0]==temp['ID'][0]

lista=temp['miRNA_ID'].tolist()
df=gse.pivot_samples('VALUE')
df['miRNA_ID']=lista
pivoted_neoplasic_samples=df.dropna().set_index('miRNA_ID', drop=True)

"""Principais variáveis que gerei:
> *neoplasic_samples* - lista das principais informações das amostras neoplasicas

> *pivoted_neoplasic_samples* - log2 da expressão dos miRNA nas amostras neoplasicas




"""

PTC_non_aggressive_GSM=neoplasic_samples[neoplasic_samples['source_name_ch1']=='PTC-non-aggressive'].index.tolist()
PTC_invasive_GSM=neoplasic_samples[neoplasic_samples['source_name_ch1']=='PTC-invasive'].index.tolist()
PTC_metastatic_GSM=neoplasic_samples[neoplasic_samples['source_name_ch1']=='PTC-metastatic'].index.tolist()

"""Média e desvio padrão por categoria histológica:"""

#PTC_non_aggressive:
pivoted_PTC_non_aggressive_samples=pivoted_neoplasic_samples[PTC_non_aggressive_GSM]
pivoted_PTC_non_aggressive_samples['Mean log2 expression']=pivoted_PTC_non_aggressive_samples.mean(axis=1)
pivoted_PTC_non_aggressive_samples['Standard Deviation log2 expression']=pivoted_PTC_non_aggressive_samples.std(axis=1)
pivoted_PTC_non_aggressive_samples_statistics=pivoted_PTC_non_aggressive_samples[['Mean log2 expression','Standard Deviation log2 expression']].dropna()
pivoted_PTC_non_aggressive_samples_statistics.sort_values(by='Mean log2 expression')

#PTC_invasive:
pivoted_PTC_invasive_samples = pivoted_neoplasic_samples[PTC_invasive_GSM]
pivoted_PTC_invasive_samples['Mean log2 expression']=pivoted_PTC_invasive_samples.mean(axis=1)
pivoted_PTC_invasive_samples['Standard Deviation log2 expression']=pivoted_PTC_invasive_samples.std(axis=1)
pivoted_PTC_invasive_samples_statistics=pivoted_PTC_invasive_samples[['Mean log2 expression','Standard Deviation log2 expression']].dropna()
pivoted_PTC_invasive_samples_statistics.sort_values(by='Mean log2 expression')

#PTC_metastatic:
pivoted_PTC_metastatic_samples = pivoted_neoplasic_samples[PTC_metastatic_GSM]
pivoted_PTC_metastatic_samples['Mean log2 expression']=pivoted_PTC_metastatic_samples.mean(axis=1)
pivoted_PTC_metastatic_samples['Standard Deviation log2 expression']=pivoted_PTC_metastatic_samples.std(axis=1)
pivoted_PTC_metastatic_samples_statistics=pivoted_PTC_metastatic_samples[['Mean log2 expression','Standard Deviation log2 expression']].dropna()
pivoted_PTC_metastatic_samples_statistics.sort_values(by='Mean log2 expression')

"""log2FC:"""

#log2FC (PTC_invasive/PTC_non_aggressive)
log2fc_PTC_invasive_against_PTC_non_aggressive=pd.DataFrame(pivoted_PTC_invasive_samples['Mean log2 expression'] - pivoted_PTC_non_aggressive_samples['Mean log2 expression'])
log2fc_PTC_invasive_against_PTC_non_aggressive.columns=['log2FC (PTC_invasive/PTC_non_aggressive)']
log2fc_PTC_invasive_against_PTC_non_aggressive=log2fc_PTC_invasive_against_PTC_non_aggressive[log2fc_PTC_invasive_against_PTC_non_aggressive.index.str.startswith('hsa')]
#log2FC (PTC_metastatic/PTC_non_aggressive)
log2fc_PTC_metastatic_against_PTC_non_aggressive=pd.DataFrame(pivoted_PTC_metastatic_samples['Mean log2 expression'] - pivoted_PTC_non_aggressive_samples['Mean log2 expression'])
log2fc_PTC_metastatic_against_PTC_non_aggressive.columns=['log2FC (PTC_metastatic/PTC_non_aggressive)']
log2fc_PTC_metastatic_against_PTC_non_aggressive=log2fc_PTC_metastatic_against_PTC_non_aggressive[log2fc_PTC_metastatic_against_PTC_non_aggressive.index.str.startswith('hsa')]
#log2FC (PTC_metastatic/PTC_invasive)
log2fc_PTC_metastatic_against_PTC_invasive=pd.DataFrame(pivoted_PTC_metastatic_samples['Mean log2 expression'] - pivoted_PTC_invasive_samples['Mean log2 expression'])
log2fc_PTC_metastatic_against_PTC_invasive.columns=['log2FC (PTC_metastatic/PTC_invasive)']
log2fc_PTC_metastatic_against_PTC_invasive=log2fc_PTC_metastatic_against_PTC_invasive[log2fc_PTC_metastatic_against_PTC_invasive.index.str.startswith('hsa')]

log2fc_PTC_metastatic_against_PTC_non_aggressive

#Thyroid_primary_tumor/Controle Teste-t:
temp1=pivoted_neoplasic_samples[PTC_metastatic_GSM].dropna()
temp1=temp1[temp1.index.str.startswith('hsa')]
temp2=pivoted_neoplasic_samples[PTC_non_aggressive_GSM].dropna()
temp2=temp2[temp2.index.str.startswith('hsa')]
temp3=log2fc_PTC_metastatic_against_PTC_non_aggressive

st, p = stats.ttest_ind(a=temp1,b=temp2, axis=1)
p_test=pd.DataFrame(data=p, index=temp1.index.tolist(), columns=['p-valor'])
b=pd.merge(temp3, p_test, how='outer', left_index=True, right_index=True )

a = statsmodels.stats.multitest.multipletests(pvals=p, method='fdr_bh')
p_test_adjusted=pd.DataFrame(data=a[1].tolist(), index=temp1.index.tolist(), columns=['p-valor ajustado'])

metastasis = pd.merge(b, p_test_adjusted, how='outer', left_index=True, right_index=True).drop_duplicates()
metastasis.sort_values(by='p-valor ajustado')

"""#GSE15740 (ainda não arrumei todo)"""

#miRNA and gene expression profiling in human thyroid carcinomas and non-neoplastic thyroids:
gse = GEOparse.get_GEO(lista_gse[14])

lista_mir=gse.gpls['GPL4717'].table['CLONE_ID'].tolist()
for i in range(len(lista_mir)):
  if type(lista_mir[i])==str:
    lista_mir[i]=lista_mir[i].lower()

gse.gsms["GSM402648"].columns

gse.phenotype_data

gse.pivot_samples('VALUE')

#Gerando a lista dos controles (safe adenoma):

controls = gse.phenotype_data['characteristics_ch1.5.disease'][gse.phenotype_data['characteristics_ch1.5.disease']=='safe (adenoma)'].index.tolist()
neoplasic_samples = gse.phenotype_data['characteristics_ch1.5.disease'][gse.phenotype_data['characteristics_ch1.5.disease']!='safe (adenoma)'].index.tolist()

temp=gse.gpls['GPL4717'].table.sort_values(by='ID')
lista=temp['CLONE_ID'].tolist()
df=gse.pivot_samples('VALUE')
df['miRNA_ID']=lista
pivoted_samples=df.dropna().set_index('miRNA_ID', drop=True)

pivoted_control_samples = pivoted_samples[controls]
pivoted_control_samples

pivoted_neoplasic_samples = pivoted_samples[neoplasic_samples]
pivoted_neoplasic_samples

pivoted_control_samples.hist()
sns.despine(offset=10, trim=True)

samples = gse.phenotype_data[['submission_date','last_update_date','characteristics_ch1.5.disease','contact_name','contact_country']]

"""Principais variáveis que gerei:
> *controls* - lista dos GSM dos controles

> *neoplasic_samples* - lista dos GSM das amostras neoplasicas

> *samples* - lista das principais informações das amostras

> *pivoted_neoplasic_samples* - log2 da expressão dos miRNA nas amostras neoplasicas

> *pivoted_control_samples* - log2 da expressão dos miRNA nas amostras controle




"""

samples['characteristics_ch1.5.disease'].unique()
#Vou dividir em 5 grupos, 1 controle e não vou usar lesional (adenoma)

#FTUMP, CPTC, WDTUMP, Control, FVPTC, FTC
lista_grupos = ['FTUMP', 'CPTC', 'WDTUMP', 'FVPTC', 'FTC']
temp=samples['characteristics_ch1.5.disease']
for i in range(len(temp)):
  for j in range(len(lista_grupos)):
    if (str(lista_grupos[j]) in str(temp[i]))==True:
      temp[i] = lista_grupos[j]
    elif ('safe (adenoma)'in str(temp[i])) == True:
      temp[i] = 'Control'
    elif ('lesional (C-PTC- mut)'in str(temp[i])) == True:
      temp[i] = 'CPTC'
    elif ('classic papillary carcinoma'in str(temp[i])) == True:
      temp[i] = 'CPTC'
    elif ('lesional (FV-PTC)'in str(temp[i])) == True:
      temp[i] = 'FVPTC'
      
grupos = pd.DataFrame(temp)

grupos['characteristics_ch1.5.disease'].unique()

FTUMP_GSM=grupos[grupos['characteristics_ch1.5.disease']=='FTUMP'].index.tolist()
CPTC_GSM=grupos[grupos['characteristics_ch1.5.disease']=='CPTC'].index.tolist()
WDTUMP_GSM=grupos[grupos['characteristics_ch1.5.disease']=='WDTUMP'].index.tolist()
FVPTC_GSM=grupos[grupos['characteristics_ch1.5.disease']=='FVPTC'].index.tolist()
FTC_GSM=grupos[grupos['characteristics_ch1.5.disease']=='FTC'].index.tolist()

"""Média e desvio padrão por categoria histológica:"""

#FTUMP:
pivoted_FTUMP_samples = gse.pivot_samples('VALUE')[FTUMP_GSM]
pivoted_FTUMP_samples['miRNAs']=lista_mir
pivoted_FTUMP_samples=pivoted_FTUMP_samples.dropna().set_index('miRNAs')
pivoted_FTUMP_samples['Mean log2 expression']=pivoted_FTUMP_samples.mean(axis=1)
pivoted_FTUMP_samples['Standard Deviation log2 expression']=pivoted_FTUMP_samples.std(axis=1)
pivoted_FTUMP_samples_statistics=pivoted_FTUMP_samples[['Mean log2 expression','Standard Deviation log2 expression']].dropna()

#CPTC:
pivoted_CPTC_samples = gse.pivot_samples('VALUE')[CPTC_GSM]
pivoted_CPTC_samples['miRNAs']=lista_mir
pivoted_CPTC_samples=pivoted_CPTC_samples.dropna().set_index('miRNAs')
pivoted_CPTC_samples['Mean log2 expression']=pivoted_CPTC_samples.mean(axis=1)
pivoted_CPTC_samples['Standard Deviation log2 expression']=pivoted_CPTC_samples.std(axis=1)
pivoted_CPTC_samples_statistics=pivoted_CPTC_samples[['Mean log2 expression','Standard Deviation log2 expression']].dropna()

#WDTUMP:
pivoted_WDTUMP_samples = gse.pivot_samples('VALUE')[WDTUMP_GSM]
pivoted_WDTUMP_samples['miRNAs']=lista_mir
pivoted_WDTUMP_samples=pivoted_WDTUMP_samples.dropna().set_index('miRNAs')
pivoted_WDTUMP_samples['Mean log2 expression']=pivoted_WDTUMP_samples.mean(axis=1)
pivoted_WDTUMP_samples['Standard Deviation log2 expression']=pivoted_WDTUMP_samples.std(axis=1)
pivoted_WDTUMP_samples_statistics=pivoted_WDTUMP_samples[['Mean log2 expression','Standard Deviation log2 expression']].dropna()

#FVPTC:
pivoted_FVPTC_samples = gse.pivot_samples('VALUE')[FVPTC_GSM]
pivoted_FVPTC_samples['miRNAs']=lista_mir
pivoted_FVPTC_samples=pivoted_FVPTC_samples.dropna().set_index('miRNAs')
pivoted_FVPTC_samples['Mean log2 expression']=pivoted_FVPTC_samples.mean(axis=1)
pivoted_FVPTC_samples['Standard Deviation log2 expression']=pivoted_FVPTC_samples.std(axis=1)
pivoted_FVPTC_samples_statistics=pivoted_FVPTC_samples[['Mean log2 expression','Standard Deviation log2 expression']].dropna()

#FTC:
pivoted_FTC_samples = gse.pivot_samples('VALUE')[FTC_GSM]
pivoted_FTC_samples['miRNAs']=lista_mir
pivoted_FTC_samples=pivoted_FTC_samples.dropna().set_index('miRNAs')
pivoted_FTC_samples['Mean log2 expression']=pivoted_FTC_samples.mean(axis=1)
pivoted_FTC_samples['Standard Deviation log2 expression']=pivoted_FTC_samples.std(axis=1)
pivoted_FTC_samples_statistics=pivoted_FTC_samples[['Mean log2 expression','Standard Deviation log2 expression']].dropna()

"""Média e desvio padrão controle:"""

#Controle:
pivoted_controls_samples = gse.pivot_samples('VALUE')[controls]
pivoted_controls_samples['miRNAs']=lista_mir
pivoted_controls_samples=pivoted_controls_samples.dropna().set_index('miRNAs')
pivoted_controls_samples['Mean log2 expression']=pivoted_controls_samples.mean(axis=1)
pivoted_controls_samples['Standard Deviation log2 expression']=pivoted_controls_samples.std(axis=1)
pivoted_controls_samples_statistics=pivoted_controls_samples[['Mean log2 expression','Standard Deviation log2 expression']].dropna()

"""Obtendo o log2FC"""

#log2FC (FTUMP/Controle)
log2fc_FTUMP_control=pd.DataFrame(pivoted_FTUMP_samples_statistics['Mean log2 expression'] - pivoted_controls_samples_statistics['Mean log2 expression'])
log2fc_FTUMP_control.columns=['log2FC (FTUMP/control)']
#log2FC (CPTC/Controle)
log2fc_CPTC_control=pd.DataFrame(pivoted_CPTC_samples_statistics['Mean log2 expression'] - pivoted_controls_samples_statistics['Mean log2 expression'])
log2fc_CPTC_control.columns=['log2FC (CPTC/control)']
#log2FC (WDTUMP/Controle)
log2fc_WDTUMP_control=pd.DataFrame(pivoted_WDTUMP_samples_statistics['Mean log2 expression'] - pivoted_controls_samples_statistics['Mean log2 expression'])
log2fc_WDTUMP_control.columns=['log2FC (WDTUMP/control)']
#log2FC (FVPTC/Controle)
log2fc_FVPTC_control=pd.DataFrame(pivoted_FVPTC_samples_statistics['Mean log2 expression'] - pivoted_controls_samples_statistics['Mean log2 expression'])
log2fc_FVPTC_control.columns=['log2FC (FVPTC/control)']
#log2FC (FTC/Controle)
log2fc_FTC_control=pd.DataFrame(pivoted_FTC_samples_statistics['Mean log2 expression'] - pivoted_controls_samples_statistics['Mean log2 expression'])
log2fc_FTC_control.columns=['log2FC (FTC/control)']

"""Tabelando os up e down regulated miR:"""

#FTUMP:
miR_upregulated_FTUMP=log2fc_FTUMP_control[log2fc_FTUMP_control>float(log2fc_FTUMP_control.quantile(0.975))].dropna()
miR_downregulated_FTUMP=log2fc_FTUMP_control[log2fc_FTUMP_control<float(log2fc_FTUMP_control.quantile(0.025))].dropna()
#CPTC:
miR_upregulated_CPTC=log2fc_CPTC_control[log2fc_CPTC_control>float(log2fc_CPTC_control.quantile(0.975))].dropna()
miR_downregulated_CPTC=log2fc_CPTC_control[log2fc_CPTC_control<float(log2fc_CPTC_control.quantile(0.025))].dropna()
#WDTUMP:
miR_upregulated_WDTUMP=log2fc_WDTUMP_control[log2fc_WDTUMP_control>float(log2fc_WDTUMP_control.quantile(0.975))].dropna()
miR_downregulated_WDTUMP=log2fc_WDTUMP_control[log2fc_WDTUMP_control<float(log2fc_WDTUMP_control.quantile(0.025))].dropna()
#FVPTC:
miR_upregulated_FVPTC=log2fc_FVPTC_control[log2fc_FVPTC_control>float(log2fc_FVPTC_control.quantile(0.975))].dropna()
miR_downregulated_FVPTC=log2fc_FVPTC_control[log2fc_FVPTC_control<float(log2fc_FVPTC_control.quantile(0.025))].dropna()
#FTC:
miR_upregulated_FTC=log2fc_FTC_control[log2fc_FTC_control>float(log2fc_FTC_control.quantile(0.975))].dropna()
miR_downregulated_FTC=log2fc_FTC_control[log2fc_FTC_control<float(log2fc_FTC_control.quantile(0.025))].dropna()

miR_FTUMP=pd.concat([miR_upregulated_FTUMP, miR_downregulated_FTUMP])
miR_CPTC=pd.concat([miR_upregulated_CPTC, miR_downregulated_CPTC])
miR_WDTUMP=pd.concat([miR_upregulated_WDTUMP, miR_downregulated_WDTUMP])
miR_FVPTC=pd.concat([miR_upregulated_FVPTC, miR_downregulated_FVPTC])
miR_FTC=pd.concat([miR_upregulated_FTC, miR_downregulated_FTC])

miR_WDTUMP.index.unique()

a=pd.merge(miR_FTUMP, miR_CPTC, how='inner', left_index=True, right_index=True)
b=pd.merge(miR_WDTUMP,miR_FVPTC, how='outer', left_index=True, right_index=True)
c=pd.merge(a,b,how='outer', left_index=True, right_index=True)
mirna_desregulados=pd.merge(c,miR_FTC,how='outer', left_index=True, right_index=True)

a

"""Final:"""

mirna_desregulados



"""#GSE97070"""

#miRNA and gene expression profiling in human thyroid carcinomas and non-neoplastic thyroids:
gse = GEOparse.get_GEO(lista_gse[41])

gse.gpls['GPL18402'].table

gse.gsms["GSM2550982"]

gse.phenotype_data

controls=gse.phenotype_data[gse.phenotype_data['characteristics_ch1.2.disease state'].str.startswith('Normal_thyroid')].index.tolist()
pivoted_control_samples = gse.pivot_samples('VALUE')[controls]
pivoted_control_samples

pivoted_control_samples.hist()
sns.despine(offset=10, trim=True)

neoplasic1=gse.phenotype_data[gse.phenotype_data['characteristics_ch1.2.disease state'].str.startswith('Thyroid_primary_tumor')]
neoplasic2=gse.phenotype_data[gse.phenotype_data['characteristics_ch1.2.disease state'].str.startswith('Thyroid_lymph_node_metastasis')]
neoplasic=pd.merge(neoplasic1, neoplasic2, how='outer', left_index=True, right_index=True).index.tolist()
pivoted_neoplasic_samples = gse.pivot_samples('VALUE')[neoplasic]
pivoted_neoplasic_samples

"""Principais variáveis que gerei:
> *controls* - lista dos GSM dos controles

> *neoplasic* - lista dos GSM das amostras neoplasicas

> *neoplasic_samples* - lista das principais informações das amostras neoplasicas

> *non_neoplasic_samples* - lista das principais informações das amostras controle

> *pivoted_neoplasic_samples* - log2 da expressão dos miRNA nas amostras neoplasicas

> *pivoted_control_samples* - log2 da expressão dos miRNA nas amostras controle




"""

PTC_lymph_node_metastasis_GSM=gse.phenotype_data[gse.phenotype_data['characteristics_ch1.2.disease state'].str.startswith('Thyroid_lymph_node_metastasis')].index.tolist()
Thyroid_primary_tumor_GSM=gse.phenotype_data[gse.phenotype_data['characteristics_ch1.2.disease state'].str.startswith('Thyroid_primary_tumor')].index.tolist()

"""Média e desvio padrão por categoria histológica:"""

#PTC_lymph_node_metastasis:
pivoted_PTC_lymph_node_metastasis_samples = pivoted_neoplasic_samples[PTC_lymph_node_metastasis_GSM]
pivoted_PTC_lymph_node_metastasis_samples['Mean log2 expression']=pivoted_PTC_lymph_node_metastasis_samples.mean(axis=1)
pivoted_PTC_lymph_node_metastasis_samples['Standard Deviation log2 expression']=pivoted_PTC_lymph_node_metastasis_samples.std(axis=1)
pivoted_PTC_lymph_node_metastasis_samples_statistics=pivoted_PTC_lymph_node_metastasis_samples[['Mean log2 expression','Standard Deviation log2 expression']].dropna()
pivoted_PTC_lymph_node_metastasis_samples_statistics

#Thyroid_primary_tumor:
Thyroid_primary_tumor_samples = pivoted_neoplasic_samples[Thyroid_primary_tumor_GSM]
Thyroid_primary_tumor_samples['Mean log2 expression']=Thyroid_primary_tumor_samples.mean(axis=1)
Thyroid_primary_tumor_samples['Standard Deviation log2 expression']=Thyroid_primary_tumor_samples.std(axis=1)
Thyroid_primary_tumor_samples_statistics=Thyroid_primary_tumor_samples[['Mean log2 expression','Standard Deviation log2 expression']].dropna()
Thyroid_primary_tumor_samples_statistics

"""Média e desvio padrão controle:"""

#Controle:
pivoted_control_samples['Mean log2 expression']=pivoted_control_samples.mean(axis=1)
pivoted_control_samples['Standard Deviation log2 expression']=pivoted_control_samples.std(axis=1)
pivoted_control_samples_statistics=pivoted_control_samples[['Mean log2 expression','Standard Deviation log2 expression']].dropna()
pivoted_control_samples_statistics

"""Obtendo o log2FC"""

#log2FC (Thyroid_primary_tumor/Controle)
log2fc_Thyroid_primary_tumor_control=pd.DataFrame(Thyroid_primary_tumor_samples_statistics['Mean log2 expression'] - pivoted_control_samples_statistics['Mean log2 expression'])
log2fc_Thyroid_primary_tumor_control.columns=['log2FC (Thyroid_primary_tumor/control)']
#log2FC (PTC_lymph_node_metastasis/Thyroid_primary_tumor)
log2fc_PTC_lymph_node_metastasis_Thyroid_primary_tumor=pd.DataFrame(pivoted_PTC_lymph_node_metastasis_samples_statistics['Mean log2 expression'] - Thyroid_primary_tumor_samples_statistics['Mean log2 expression'])
log2fc_PTC_lymph_node_metastasis_Thyroid_primary_tumor.columns=['log2FC (PTC_lymph_node_metastasis/Thyroid_primary_tumor)']
#log2FC (PTC_lymph_node_metastasis/Controle)
log2fc_PTC_lymph_node_metastasis_control=pd.DataFrame(pivoted_PTC_lymph_node_metastasis_samples_statistics['Mean log2 expression'] - pivoted_control_samples_statistics['Mean log2 expression'])
log2fc_PTC_lymph_node_metastasis_control.columns=['log2FC (PTC lymph node metastasis/control)']

"""Tabelando os up e down regulated miR:"""

temp2

#Thyroid_primary_tumor/Controle Teste-t:
temp1=pivoted_neoplasic_samples[PTC_lymph_node_metastasis_GSM]
temp2=pivoted_control_samples[controls]
temp3=log2fc_PTC_lymph_node_metastasis_control

st, p = stats.ttest_ind(a=temp1,b=temp2, axis=1)
p_test=pd.DataFrame(data=p, index=temp1.index.tolist(), columns=['p-valor'])
b=pd.merge(temp3, p_test, how='outer', left_index=True, right_index=True )

a = statsmodels.stats.multitest.multipletests(pvals=p, method='fdr_bh')
p_test_adjusted=pd.DataFrame(data=a[1].tolist(), index=temp1.index.tolist(), columns=['p-valor ajustado'])

metastasis = pd.merge(b, p_test_adjusted, how='outer', left_index=True, right_index=True).drop_duplicates()
metastasis=metastasis[metastasis.index.str.startswith('hsa')].sort_values(by='log2FC (PTC lymph node metastasis/control)')
metastasis=metastasis[metastasis['p-valor ajustado']<0.05]
metastasis

"""#PTC lymph node metastasis x control GSE97070 versus PTC lymph node metastasis - GSE104006:"""

df1=pd.read_excel("/content/drive/My Drive/IC/Tabelas GEO/PTC lymph node metastasis x control GSE97070.xlsx")
df2=pd.read_excel("/content/drive/My Drive/IC/Tabelas GEO/PTC lymph node metastasis - GSE104006.xlsx")

table=pd.merge(df1, df2, how='inner', left_on='ID_REF', right_on='ID_REF', suffixes=(' GSE97070', ' GSE104006'))
table[table['log2FC (PTC lymph node metastasis/control) GSE97070']<-1]



"""#cBioPortal:"""

df1=pd.read_csv("/content/drive/My Drive/genie_public_clinical_data.tsv", delimiter="\t")
df1=df1[df1['Sample Type']=='Metastasis']
len(df1)

df2=pd.read_csv("/content/drive/My Drive/Mutated_Genes.txt", delimiter="\t")
a=df2['#'].apply(lambda x: (x-df2['#'].mean())/df2['#'].std())
a=pd.DataFrame(data=a)
b=pd.merge(a, df2, how='inner', left_index=True, right_index=True)
b[['Gene','#_x']]

from numpy.random import seed
from numpy.random import randn
from matplotlib import pyplot

df3=pd.read_csv("/content/drive/My Drive/Mutated_Genes (1).txt", delimiter="\t")
a=df3['#'].apply(lambda x: (x-df3['#'].mean())/df3['#'].std())
a=pd.DataFrame(data=a)
b=pd.merge(a, df3, how='inner', left_index=True, right_index=True)
b=b[['Gene','#_x']]
b=b[b['#_x']>1]
b

df3['Gene']

